//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class alerts
    {
        public int alert_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> folder_id { get; set; }
        public int type_id { get; set; }
        public Nullable<int> view_id { get; set; }
        public sbyte alert_type { get; set; }
        public Nullable<sbyte> alert_frequency { get; set; }
        public Nullable<int> stamp_id { get; set; }
    
        public virtual folders folders { get; set; }
        public virtual projects projects { get; set; }
        public virtual issue_types issue_types { get; set; }
        public virtual users users { get; set; }
        public virtual views views { get; set; }
    }
}
