//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class attr_values
    {
        public int issue_id { get; set; }
        public int attr_id { get; set; }
        public string attr_value { get; set; }
    
        public virtual attr_types attr_types { get; set; }
        public virtual issues issues { get; set; }
    }
}
