//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_inboxes
    {
        public email_inboxes()
        {
            this.subscriptions = new HashSet<subscriptions>();
        }
    
        public int inbox_id { get; set; }
        public string inbox_engine { get; set; }
        public string inbox_email { get; set; }
        public string inbox_server { get; set; }
        public int inbox_port { get; set; }
        public string inbox_encryption { get; set; }
        public string inbox_user { get; set; }
        public string inbox_password { get; set; }
        public string inbox_mailbox { get; set; }
        public sbyte inbox_no_validate { get; set; }
        public sbyte inbox_leave_messages { get; set; }
        public sbyte inbox_allow_external { get; set; }
        public Nullable<int> inbox_robot { get; set; }
        public sbyte inbox_map_folder { get; set; }
        public Nullable<int> inbox_default_folder { get; set; }
        public sbyte inbox_respond { get; set; }
        public sbyte inbox_subscribe { get; set; }
        public sbyte inbox_format { get; set; }
    
        public virtual folders folders { get; set; }
        public virtual users users { get; set; }
        public virtual ICollection<subscriptions> subscriptions { get; set; }
    }
}
