//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_issue_history
    {
        public long his_id { get; set; }
        public long his_iss_id { get; set; }
        public long his_usr_id { get; set; }
        public System.DateTime his_created_date { get; set; }
        public string his_summary { get; set; }
        public sbyte his_htt_id { get; set; }
        public bool his_is_hidden { get; set; }
    }
}
