//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_project_status_date
    {
        public long psd_id { get; set; }
        public long psd_prj_id { get; set; }
        public long psd_sta_id { get; set; }
        public string psd_date_field { get; set; }
        public string psd_label { get; set; }
    }
}
