//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_reminder_action
    {
        public long rma_id { get; set; }
        public long rma_rem_id { get; set; }
        public byte rma_rmt_id { get; set; }
        public System.DateTime rma_created_date { get; set; }
        public Nullable<System.DateTime> rma_last_updated_date { get; set; }
        public string rma_title { get; set; }
        public byte rma_rank { get; set; }
        public bool rma_alert_irc { get; set; }
        public bool rma_alert_group_leader { get; set; }
        public string rma_boilerplate { get; set; }
    }
}
