//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_customer_account_manager
    {
        public long cam_id { get; set; }
        public long cam_prj_id { get; set; }
        public long cam_customer_id { get; set; }
        public long cam_usr_id { get; set; }
        public string cam_type { get; set; }
    }
}
