//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_reminder_level_condition
    {
        public long rlc_id { get; set; }
        public long rlc_rma_id { get; set; }
        public byte rlc_rmf_id { get; set; }
        public bool rlc_rmo_id { get; set; }
        public System.DateTime rlc_created_date { get; set; }
        public Nullable<System.DateTime> rlc_last_updated_date { get; set; }
        public string rlc_value { get; set; }
        public Nullable<byte> rlc_comparison_rmf_id { get; set; }
    }
}
