//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_issue_user_replier
    {
        public long iur_id { get; set; }
        public long iur_iss_id { get; set; }
        public long iur_usr_id { get; set; }
        public string iur_email { get; set; }
    }
}
