//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_reminder_requirement
    {
        public long rer_id { get; set; }
        public long rer_rem_id { get; set; }
        public Nullable<long> rer_iss_id { get; set; }
        public Nullable<long> rer_support_level_id { get; set; }
        public Nullable<long> rer_customer_id { get; set; }
        public bool rer_trigger_all_issues { get; set; }
    }
}
