//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u49299178_Entities1 : DbContext
    {
        public u49299178_Entities1()
            : base("name=u49299178_Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<eventum_columns_to_display> eventum_columns_to_display { get; set; }
        public DbSet<eventum_custom_field> eventum_custom_field { get; set; }
        public DbSet<eventum_custom_field_option> eventum_custom_field_option { get; set; }
        public DbSet<eventum_custom_filter> eventum_custom_filter { get; set; }
        public DbSet<eventum_customer_account_manager> eventum_customer_account_manager { get; set; }
        public DbSet<eventum_customer_note> eventum_customer_note { get; set; }
        public DbSet<eventum_email_account> eventum_email_account { get; set; }
        public DbSet<eventum_email_draft> eventum_email_draft { get; set; }
        public DbSet<eventum_email_draft_recipient> eventum_email_draft_recipient { get; set; }
        public DbSet<eventum_email_response> eventum_email_response { get; set; }
        public DbSet<eventum_faq> eventum_faq { get; set; }
        public DbSet<eventum_faq_support_level> eventum_faq_support_level { get; set; }
        public DbSet<eventum_group> eventum_group { get; set; }
        public DbSet<eventum_history_type> eventum_history_type { get; set; }
        public DbSet<eventum_irc_notice> eventum_irc_notice { get; set; }
        public DbSet<eventum_issue> eventum_issue { get; set; }
        public DbSet<eventum_issue_attachment> eventum_issue_attachment { get; set; }
        public DbSet<eventum_issue_attachment_file> eventum_issue_attachment_file { get; set; }
        public DbSet<eventum_issue_checkin> eventum_issue_checkin { get; set; }
        public DbSet<eventum_issue_custom_field> eventum_issue_custom_field { get; set; }
        public DbSet<eventum_issue_history> eventum_issue_history { get; set; }
        public DbSet<eventum_issue_quarantine> eventum_issue_quarantine { get; set; }
        public DbSet<eventum_issue_requirement> eventum_issue_requirement { get; set; }
        public DbSet<eventum_issue_user> eventum_issue_user { get; set; }
        public DbSet<eventum_issue_user_replier> eventum_issue_user_replier { get; set; }
        public DbSet<eventum_link_filter> eventum_link_filter { get; set; }
        public DbSet<eventum_mail_queue> eventum_mail_queue { get; set; }
        public DbSet<eventum_mail_queue_log> eventum_mail_queue_log { get; set; }
        public DbSet<eventum_news> eventum_news { get; set; }
        public DbSet<eventum_note> eventum_note { get; set; }
        public DbSet<eventum_phone_support> eventum_phone_support { get; set; }
        public DbSet<eventum_project> eventum_project { get; set; }
        public DbSet<eventum_project_category> eventum_project_category { get; set; }
        public DbSet<eventum_project_custom_field> eventum_project_custom_field { get; set; }
        public DbSet<eventum_project_email_response> eventum_project_email_response { get; set; }
        public DbSet<eventum_project_field_display> eventum_project_field_display { get; set; }
        public DbSet<eventum_project_group> eventum_project_group { get; set; }
        public DbSet<eventum_project_link_filter> eventum_project_link_filter { get; set; }
        public DbSet<eventum_project_news> eventum_project_news { get; set; }
        public DbSet<eventum_project_phone_category> eventum_project_phone_category { get; set; }
        public DbSet<eventum_project_priority> eventum_project_priority { get; set; }
        public DbSet<eventum_project_release> eventum_project_release { get; set; }
        public DbSet<eventum_project_round_robin> eventum_project_round_robin { get; set; }
        public DbSet<eventum_project_status> eventum_project_status { get; set; }
        public DbSet<eventum_project_status_date> eventum_project_status_date { get; set; }
        public DbSet<eventum_project_user> eventum_project_user { get; set; }
        public DbSet<eventum_reminder_action> eventum_reminder_action { get; set; }
        public DbSet<eventum_reminder_action_type> eventum_reminder_action_type { get; set; }
        public DbSet<eventum_reminder_field> eventum_reminder_field { get; set; }
        public DbSet<eventum_reminder_history> eventum_reminder_history { get; set; }
        public DbSet<eventum_reminder_level> eventum_reminder_level { get; set; }
        public DbSet<eventum_reminder_level_condition> eventum_reminder_level_condition { get; set; }
        public DbSet<eventum_reminder_operator> eventum_reminder_operator { get; set; }
        public DbSet<eventum_reminder_priority> eventum_reminder_priority { get; set; }
        public DbSet<eventum_reminder_requirement> eventum_reminder_requirement { get; set; }
        public DbSet<eventum_reminder_triggered_action> eventum_reminder_triggered_action { get; set; }
        public DbSet<eventum_resolution> eventum_resolution { get; set; }
        public DbSet<eventum_search_profile> eventum_search_profile { get; set; }
        public DbSet<eventum_status> eventum_status { get; set; }
        public DbSet<eventum_subscription> eventum_subscription { get; set; }
        public DbSet<eventum_subscription_type> eventum_subscription_type { get; set; }
        public DbSet<eventum_support_email> eventum_support_email { get; set; }
        public DbSet<eventum_support_email_body> eventum_support_email_body { get; set; }
        public DbSet<eventum_time_tracking> eventum_time_tracking { get; set; }
        public DbSet<eventum_time_tracking_category> eventum_time_tracking_category { get; set; }
        public DbSet<eventum_user> eventum_user { get; set; }
        public DbSet<eventum_issue_association> eventum_issue_association { get; set; }
        public DbSet<eventum_reminder_action_list> eventum_reminder_action_list { get; set; }
        public DbSet<eventum_round_robin_user> eventum_round_robin_user { get; set; }
        public DbSet<eventum_user_alias> eventum_user_alias { get; set; }
        public DbSet<eventum_version> eventum_version { get; set; }
    }
}
