//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_project_round_robin
    {
        public long prr_id { get; set; }
        public long prr_prj_id { get; set; }
        public System.TimeSpan prr_blackout_start { get; set; }
        public System.TimeSpan prr_blackout_end { get; set; }
    }
}
