//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_issue_checkin
    {
        public long isc_id { get; set; }
        public long isc_iss_id { get; set; }
        public string isc_module { get; set; }
        public string isc_filename { get; set; }
        public string isc_old_version { get; set; }
        public string isc_new_version { get; set; }
        public System.DateTime isc_created_date { get; set; }
        public string isc_username { get; set; }
        public string isc_commit_msg { get; set; }
    }
}
