//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_columns_to_display
    {
        public long ctd_prj_id { get; set; }
        public string ctd_page { get; set; }
        public string ctd_field { get; set; }
        public bool ctd_min_role { get; set; }
        public sbyte ctd_rank { get; set; }
    }
}
