//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_email_account
    {
        public long ema_id { get; set; }
        public long ema_prj_id { get; set; }
        public string ema_type { get; set; }
        public string ema_folder { get; set; }
        public string ema_hostname { get; set; }
        public string ema_port { get; set; }
        public string ema_username { get; set; }
        public string ema_password { get; set; }
        public int ema_get_only_new { get; set; }
        public int ema_leave_copy { get; set; }
        public string ema_issue_auto_creation { get; set; }
        public string ema_issue_auto_creation_options { get; set; }
        public Nullable<bool> ema_use_routing { get; set; }
    }
}
