//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_issue_attachment_file
    {
        public long iaf_id { get; set; }
        public long iaf_iat_id { get; set; }
        public byte[] iaf_file { get; set; }
        public string iaf_filename { get; set; }
        public string iaf_filetype { get; set; }
        public string iaf_filesize { get; set; }
    }
}
