//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_faq
    {
        public long faq_id { get; set; }
        public long faq_prj_id { get; set; }
        public long faq_usr_id { get; set; }
        public System.DateTime faq_created_date { get; set; }
        public Nullable<System.DateTime> faq_updated_date { get; set; }
        public string faq_title { get; set; }
        public string faq_message { get; set; }
        public byte faq_rank { get; set; }
    }
}
