//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_reminder_level
    {
        public long rem_id { get; set; }
        public System.DateTime rem_created_date { get; set; }
        public bool rem_rank { get; set; }
        public Nullable<System.DateTime> rem_last_updated_date { get; set; }
        public string rem_title { get; set; }
        public long rem_prj_id { get; set; }
        public bool rem_skip_weekend { get; set; }
    }
}
