//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_irc_notice
    {
        public long ino_id { get; set; }
        public int ino_prj_id { get; set; }
        public long ino_iss_id { get; set; }
        public System.DateTime ino_created_date { get; set; }
        public string ino_message { get; set; }
        public string ino_status { get; set; }
    }
}
