//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_project
    {
        public long prj_id { get; set; }
        public System.DateTime prj_created_date { get; set; }
        public string prj_title { get; set; }
        public string prj_status { get; set; }
        public long prj_lead_usr_id { get; set; }
        public long prj_initial_sta_id { get; set; }
        public string prj_remote_invocation { get; set; }
        public string prj_anonymous_post { get; set; }
        public string prj_anonymous_post_options { get; set; }
        public string prj_outgoing_sender_name { get; set; }
        public string prj_outgoing_sender_email { get; set; }
        public string prj_mail_aliases { get; set; }
        public string prj_customer_backend { get; set; }
        public string prj_workflow_backend { get; set; }
        public Nullable<bool> prj_segregate_reporter { get; set; }
    }
}
