//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_phone_support
    {
        public long phs_id { get; set; }
        public long phs_usr_id { get; set; }
        public long phs_iss_id { get; set; }
        public Nullable<long> phs_ttr_id { get; set; }
        public string phs_call_from_lname { get; set; }
        public string phs_call_from_fname { get; set; }
        public string phs_call_to_lname { get; set; }
        public string phs_call_to_fname { get; set; }
        public System.DateTime phs_created_date { get; set; }
        public string phs_type { get; set; }
        public string phs_phone_number { get; set; }
        public string phs_phone_type { get; set; }
        public long phs_phc_id { get; set; }
        public string phs_description { get; set; }
    }
}
