//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_search_profile
    {
        public long sep_id { get; set; }
        public long sep_usr_id { get; set; }
        public long sep_prj_id { get; set; }
        public string sep_type { get; set; }
        public byte[] sep_user_profile { get; set; }
    }
}
