//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_custom_filter
    {
        public long cst_id { get; set; }
        public long cst_usr_id { get; set; }
        public long cst_prj_id { get; set; }
        public string cst_title { get; set; }
        public Nullable<long> cst_iss_pri_id { get; set; }
        public string cst_keywords { get; set; }
        public string cst_users { get; set; }
        public Nullable<long> cst_reporter { get; set; }
        public Nullable<long> cst_iss_prc_id { get; set; }
        public Nullable<long> cst_iss_sta_id { get; set; }
        public Nullable<long> cst_iss_pre_id { get; set; }
        public string cst_show_authorized { get; set; }
        public string cst_show_notification_list { get; set; }
        public Nullable<System.DateTime> cst_created_date { get; set; }
        public string cst_created_date_filter_type { get; set; }
        public Nullable<short> cst_created_date_time_period { get; set; }
        public Nullable<System.DateTime> cst_created_date_end { get; set; }
        public Nullable<System.DateTime> cst_updated_date { get; set; }
        public string cst_updated_date_filter_type { get; set; }
        public Nullable<short> cst_updated_date_time_period { get; set; }
        public Nullable<System.DateTime> cst_updated_date_end { get; set; }
        public Nullable<System.DateTime> cst_last_response_date { get; set; }
        public string cst_last_response_date_filter_type { get; set; }
        public Nullable<short> cst_last_response_date_time_period { get; set; }
        public Nullable<System.DateTime> cst_last_response_date_end { get; set; }
        public Nullable<System.DateTime> cst_first_response_date { get; set; }
        public string cst_first_response_date_filter_type { get; set; }
        public Nullable<short> cst_first_response_date_time_period { get; set; }
        public Nullable<System.DateTime> cst_first_response_date_end { get; set; }
        public Nullable<System.DateTime> cst_closed_date { get; set; }
        public string cst_closed_date_filter_type { get; set; }
        public Nullable<short> cst_closed_date_time_period { get; set; }
        public Nullable<System.DateTime> cst_closed_date_end { get; set; }
        public string cst_rows { get; set; }
        public string cst_sort_by { get; set; }
        public string cst_sort_order { get; set; }
        public Nullable<int> cst_hide_closed { get; set; }
        public Nullable<int> cst_is_global { get; set; }
        public string cst_search_type { get; set; }
        public string cst_custom_field { get; set; }
    }
}
