//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_issue_attachment
    {
        public long iat_id { get; set; }
        public long iat_iss_id { get; set; }
        public long iat_usr_id { get; set; }
        public System.DateTime iat_created_date { get; set; }
        public string iat_description { get; set; }
        public string iat_unknown_user { get; set; }
        public string iat_status { get; set; }
        public Nullable<long> iat_not_id { get; set; }
    }
}
