//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_custom_field
    {
        public long fld_id { get; set; }
        public string fld_title { get; set; }
        public string fld_description { get; set; }
        public string fld_type { get; set; }
        public int fld_report_form { get; set; }
        public int fld_report_form_required { get; set; }
        public int fld_anonymous_form { get; set; }
        public int fld_anonymous_form_required { get; set; }
        public bool fld_close_form { get; set; }
        public bool fld_close_form_required { get; set; }
        public bool fld_list_display { get; set; }
        public bool fld_min_role { get; set; }
        public short fld_rank { get; set; }
        public string fld_backend { get; set; }
    }
}
