//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_time_tracking
    {
        public long ttr_id { get; set; }
        public long ttr_ttc_id { get; set; }
        public long ttr_iss_id { get; set; }
        public long ttr_usr_id { get; set; }
        public System.DateTime ttr_created_date { get; set; }
        public long ttr_time_spent { get; set; }
        public string ttr_summary { get; set; }
    }
}
