//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_email_draft
    {
        public long emd_id { get; set; }
        public long emd_usr_id { get; set; }
        public long emd_iss_id { get; set; }
        public Nullable<long> emd_sup_id { get; set; }
        public string emd_status { get; set; }
        public System.DateTime emd_updated_date { get; set; }
        public string emd_subject { get; set; }
        public string emd_body { get; set; }
        public string emd_unknown_user { get; set; }
    }
}
