//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_customer_note
    {
        public long cno_id { get; set; }
        public long cno_prj_id { get; set; }
        public long cno_customer_id { get; set; }
        public System.DateTime cno_created_date { get; set; }
        public Nullable<System.DateTime> cno_updated_date { get; set; }
        public string cno_note { get; set; }
    }
}
