//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_news
    {
        public long nws_id { get; set; }
        public long nws_usr_id { get; set; }
        public System.DateTime nws_created_date { get; set; }
        public string nws_title { get; set; }
        public string nws_message { get; set; }
        public string nws_status { get; set; }
    }
}
