//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_email_draft_recipient
    {
        public long edr_id { get; set; }
        public long edr_emd_id { get; set; }
        public bool edr_is_cc { get; set; }
        public string edr_email { get; set; }
    }
}
