//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_round_robin_user
    {
        public long rru_prr_id { get; set; }
        public long rru_usr_id { get; set; }
        public Nullable<bool> rru_next { get; set; }
    }
}
