//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_project_release
    {
        public long pre_id { get; set; }
        public long pre_prj_id { get; set; }
        public string pre_title { get; set; }
        public System.DateTime pre_scheduled_date { get; set; }
        public string pre_status { get; set; }
    }
}
