//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_mail_queue_log
    {
        public long mql_id { get; set; }
        public long mql_maq_id { get; set; }
        public System.DateTime mql_created_date { get; set; }
        public string mql_status { get; set; }
        public string mql_server_message { get; set; }
    }
}
