//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_issue_custom_field
    {
        public long icf_id { get; set; }
        public long icf_iss_id { get; set; }
        public long icf_fld_id { get; set; }
        public string icf_value { get; set; }
        public Nullable<int> icf_value_integer { get; set; }
        public Nullable<System.DateTime> icf_value_date { get; set; }
    }
}
