//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_mail_queue
    {
        public long maq_id { get; set; }
        public Nullable<long> maq_iss_id { get; set; }
        public System.DateTime maq_queued_date { get; set; }
        public string maq_status { get; set; }
        public bool maq_save_copy { get; set; }
        public string maq_sender_ip_address { get; set; }
        public string maq_recipient { get; set; }
        public string maq_subject { get; set; }
        public string maq_headers { get; set; }
        public byte[] maq_body { get; set; }
        public string maq_type { get; set; }
        public Nullable<long> maq_usr_id { get; set; }
        public Nullable<long> maq_type_id { get; set; }
    }
}
