//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_project_priority
    {
        public int pri_id { get; set; }
        public long pri_prj_id { get; set; }
        public string pri_title { get; set; }
        public bool pri_rank { get; set; }
    }
}
