//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_user
    {
        public long usr_id { get; set; }
        public Nullable<long> usr_grp_id { get; set; }
        public Nullable<long> usr_customer_id { get; set; }
        public Nullable<long> usr_customer_contact_id { get; set; }
        public System.DateTime usr_created_date { get; set; }
        public string usr_status { get; set; }
        public string usr_password { get; set; }
        public string usr_full_name { get; set; }
        public string usr_email { get; set; }
        public string usr_preferences { get; set; }
        public string usr_sms_email { get; set; }
        public Nullable<bool> usr_clocked_in { get; set; }
        public string usr_lang { get; set; }
    }
}
