//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_support_email
    {
        public long sup_id { get; set; }
        public long sup_ema_id { get; set; }
        public long sup_parent_id { get; set; }
        public Nullable<long> sup_iss_id { get; set; }
        public Nullable<long> sup_usr_id { get; set; }
        public Nullable<long> sup_customer_id { get; set; }
        public string sup_message_id { get; set; }
        public System.DateTime sup_date { get; set; }
        public string sup_from { get; set; }
        public string sup_to { get; set; }
        public string sup_cc { get; set; }
        public string sup_subject { get; set; }
        public bool sup_has_attachment { get; set; }
        public bool sup_removed { get; set; }
    }
}
