//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventum_reminder_field
    {
        public byte rmf_id { get; set; }
        public string rmf_title { get; set; }
        public string rmf_sql_field { get; set; }
        public string rmf_sql_representation { get; set; }
        public Nullable<bool> rmf_allow_column_compare { get; set; }
    }
}
