//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class folders
    {
        public folders()
        {
            this.alerts = new HashSet<alerts>();
            this.changes = new HashSet<changes>();
            this.changes1 = new HashSet<changes>();
            this.email_inboxes = new HashSet<email_inboxes>();
            this.issue_stubs = new HashSet<issue_stubs>();
            this.issues = new HashSet<issues>();
        }
    
        public int folder_id { get; set; }
        public int project_id { get; set; }
        public int type_id { get; set; }
        public string folder_name { get; set; }
        public Nullable<int> stamp_id { get; set; }
    
        public virtual ICollection<alerts> alerts { get; set; }
        public virtual ICollection<changes> changes { get; set; }
        public virtual ICollection<changes> changes1 { get; set; }
        public virtual ICollection<email_inboxes> email_inboxes { get; set; }
        public virtual projects projects { get; set; }
        public virtual issue_types issue_types { get; set; }
        public virtual ICollection<issue_stubs> issue_stubs { get; set; }
        public virtual ICollection<issues> issues { get; set; }
    }
}
