//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_stubs
    {
        public int stub_id { get; set; }
        public int prev_id { get; set; }
        public int issue_id { get; set; }
        public int folder_id { get; set; }
    
        public virtual folders folders { get; set; }
        public virtual stamps stamps { get; set; }
    }
}
