//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_types
    {
        public issue_types()
        {
            this.alerts = new HashSet<alerts>();
            this.attr_types = new HashSet<attr_types>();
            this.folders = new HashSet<folders>();
            this.view_preferences = new HashSet<view_preferences>();
            this.view_settings = new HashSet<view_settings>();
            this.views = new HashSet<views>();
        }
    
        public int type_id { get; set; }
        public string type_name { get; set; }
    
        public virtual ICollection<alerts> alerts { get; set; }
        public virtual ICollection<attr_types> attr_types { get; set; }
        public virtual ICollection<folders> folders { get; set; }
        public virtual ICollection<view_preferences> view_preferences { get; set; }
        public virtual ICollection<view_settings> view_settings { get; set; }
        public virtual ICollection<views> views { get; set; }
    }
}
