//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class issues
    {
        public issues()
        {
            this.attr_values = new HashSet<attr_values>();
            this.change_stubs = new HashSet<change_stubs>();
            this.changes = new HashSet<changes>();
            this.issue_states = new HashSet<issue_states>();
            this.subscriptions = new HashSet<subscriptions>();
        }
    
        public int issue_id { get; set; }
        public int folder_id { get; set; }
        public string issue_name { get; set; }
        public int stamp_id { get; set; }
        public Nullable<int> stub_id { get; set; }
        public Nullable<int> descr_id { get; set; }
        public Nullable<int> descr_stub_id { get; set; }
    
        public virtual ICollection<attr_values> attr_values { get; set; }
        public virtual ICollection<change_stubs> change_stubs { get; set; }
        public virtual ICollection<changes> changes { get; set; }
        public virtual folders folders { get; set; }
        public virtual issue_descriptions issue_descriptions { get; set; }
        public virtual ICollection<issue_states> issue_states { get; set; }
        public virtual stamps stamps { get; set; }
        public virtual stamps stamps1 { get; set; }
        public virtual ICollection<subscriptions> subscriptions { get; set; }
    }
}
