//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_descriptions
    {
        public int issue_id { get; set; }
        public string descr_text { get; set; }
        public sbyte descr_format { get; set; }
    
        public virtual issues issues { get; set; }
    }
}
