//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_events
    {
        public int event_id { get; set; }
        public string event_type { get; set; }
        public sbyte event_severity { get; set; }
        public string event_message { get; set; }
        public int event_time { get; set; }
        public Nullable<int> user_id { get; set; }
        public string host_name { get; set; }
    
        public virtual users users { get; set; }
    }
}
