//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_bug_relationship
    {
        public long id { get; set; }
        public long source_bug_id { get; set; }
        public long destination_bug_id { get; set; }
        public short relationship_type { get; set; }
    }
}
