//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_bug_text
    {
        public long id { get; set; }
        public string description { get; set; }
        public string steps_to_reproduce { get; set; }
        public string additional_information { get; set; }
    }
}
