//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_bugnote
    {
        public long id { get; set; }
        public long bug_id { get; set; }
        public long reporter_id { get; set; }
        public long bugnote_text_id { get; set; }
        public short view_state { get; set; }
        public Nullable<int> note_type { get; set; }
        public string note_attr { get; set; }
        public long time_tracking { get; set; }
        public long last_modified { get; set; }
        public long date_submitted { get; set; }
    }
}
