//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_bug
    {
        public long id { get; set; }
        public long project_id { get; set; }
        public long reporter_id { get; set; }
        public long handler_id { get; set; }
        public long duplicate_id { get; set; }
        public short priority { get; set; }
        public short severity { get; set; }
        public short reproducibility { get; set; }
        public short status { get; set; }
        public short resolution { get; set; }
        public short projection { get; set; }
        public short eta { get; set; }
        public long bug_text_id { get; set; }
        public string os { get; set; }
        public string os_build { get; set; }
        public string platform { get; set; }
        public string version { get; set; }
        public string fixed_in_version { get; set; }
        public string build { get; set; }
        public long profile_id { get; set; }
        public short view_state { get; set; }
        public string summary { get; set; }
        public int sponsorship_total { get; set; }
        public sbyte sticky { get; set; }
        public string target_version { get; set; }
        public long category_id { get; set; }
        public long date_submitted { get; set; }
        public long due_date { get; set; }
        public long last_updated { get; set; }
    }
}
