//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_category
    {
        public long id { get; set; }
        public long project_id { get; set; }
        public long user_id { get; set; }
        public string name { get; set; }
        public long status { get; set; }
    }
}
