//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_email
    {
        public long email_id { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public string metadata { get; set; }
        public string body { get; set; }
        public long submitted { get; set; }
    }
}
