//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_project_file
    {
        public long id { get; set; }
        public long project_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string diskfile { get; set; }
        public string filename { get; set; }
        public string folder { get; set; }
        public int filesize { get; set; }
        public string file_type { get; set; }
        public byte[] content { get; set; }
        public long date_added { get; set; }
        public long user_id { get; set; }
    }
}
