//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_project
    {
        public long id { get; set; }
        public string name { get; set; }
        public short status { get; set; }
        public sbyte enabled { get; set; }
        public short view_state { get; set; }
        public short access_min { get; set; }
        public string file_path { get; set; }
        public string description { get; set; }
        public long category_id { get; set; }
        public sbyte inherit_global { get; set; }
    }
}
