//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_user
    {
        public long id { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public sbyte enabled { get; set; }
        public sbyte @protected { get; set; }
        public short access_level { get; set; }
        public int login_count { get; set; }
        public short lost_password_request_count { get; set; }
        public short failed_login_count { get; set; }
        public string cookie_string { get; set; }
        public long last_visit { get; set; }
        public long date_created { get; set; }
    }
}
