//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_user_profile
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string platform { get; set; }
        public string os { get; set; }
        public string os_build { get; set; }
        public string description { get; set; }
    }
}
