//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_user_pref
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public long project_id { get; set; }
        public long default_profile { get; set; }
        public long default_project { get; set; }
        public int refresh_delay { get; set; }
        public int redirect_delay { get; set; }
        public string bugnote_order { get; set; }
        public sbyte email_on_new { get; set; }
        public sbyte email_on_assigned { get; set; }
        public sbyte email_on_feedback { get; set; }
        public sbyte email_on_resolved { get; set; }
        public sbyte email_on_closed { get; set; }
        public sbyte email_on_reopened { get; set; }
        public sbyte email_on_bugnote { get; set; }
        public sbyte email_on_status { get; set; }
        public sbyte email_on_priority { get; set; }
        public short email_on_priority_min_severity { get; set; }
        public short email_on_status_min_severity { get; set; }
        public short email_on_bugnote_min_severity { get; set; }
        public short email_on_reopened_min_severity { get; set; }
        public short email_on_closed_min_severity { get; set; }
        public short email_on_resolved_min_severity { get; set; }
        public short email_on_feedback_min_severity { get; set; }
        public short email_on_assigned_min_severity { get; set; }
        public short email_on_new_min_severity { get; set; }
        public short email_bugnote_limit { get; set; }
        public string language { get; set; }
        public string timezone { get; set; }
    }
}
