//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferences
    {
        public int user_id { get; set; }
        public string pref_key { get; set; }
        public string pref_value { get; set; }
    
        public virtual users users { get; set; }
    }
}
