//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class register_requests
    {
        public int request_id { get; set; }
        public string user_login { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_passwd { get; set; }
        public string request_key { get; set; }
        public int created_time { get; set; }
        public sbyte is_active { get; set; }
        public sbyte is_sent { get; set; }
    }
}
