//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class stamps
    {
        public stamps()
        {
            this.issues1 = new HashSet<issues>();
        }
    
        public int stamp_id { get; set; }
        public int user_id { get; set; }
        public int stamp_time { get; set; }
    
        public virtual change_stubs change_stubs { get; set; }
        public virtual changes changes { get; set; }
        public virtual issue_stubs issue_stubs { get; set; }
        public virtual issues issues { get; set; }
        public virtual ICollection<issues> issues1 { get; set; }
        public virtual users users { get; set; }
    }
}
