//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriptions
    {
        public int subscription_id { get; set; }
        public int issue_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_email { get; set; }
        public int stamp_id { get; set; }
        public Nullable<int> inbox_id { get; set; }
    
        public virtual email_inboxes email_inboxes { get; set; }
        public virtual issues issues { get; set; }
        public virtual users users { get; set; }
    }
}
