//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class views
    {
        public views()
        {
            this.alerts = new HashSet<alerts>();
        }
    
        public int view_id { get; set; }
        public int type_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string view_name { get; set; }
        public string view_def { get; set; }
    
        public virtual ICollection<alerts> alerts { get; set; }
        public virtual issue_types issue_types { get; set; }
        public virtual users users { get; set; }
    }
}
