//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_settings
    {
        public int type_id { get; set; }
        public string set_key { get; set; }
        public string set_value { get; set; }
    
        public virtual issue_types issue_types { get; set; }
    }
}
