//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMigrate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webissuesEntities : DbContext
    {
        public webissuesEntities()
            : base("name=webissuesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alerts> alerts { get; set; }
        public DbSet<attr_types> attr_types { get; set; }
        public DbSet<attr_values> attr_values { get; set; }
        public DbSet<change_stubs> change_stubs { get; set; }
        public DbSet<changes> changes { get; set; }
        public DbSet<comments> comments { get; set; }
        public DbSet<email_inboxes> email_inboxes { get; set; }
        public DbSet<files> files { get; set; }
        public DbSet<folders> folders { get; set; }
        public DbSet<issue_descriptions> issue_descriptions { get; set; }
        public DbSet<issue_states> issue_states { get; set; }
        public DbSet<issue_stubs> issue_stubs { get; set; }
        public DbSet<issue_types> issue_types { get; set; }
        public DbSet<issues> issues { get; set; }
        public DbSet<log_events> log_events { get; set; }
        public DbSet<preferences> preferences { get; set; }
        public DbSet<project_descriptions> project_descriptions { get; set; }
        public DbSet<projects> projects { get; set; }
        public DbSet<register_requests> register_requests { get; set; }
        public DbSet<rights> rights { get; set; }
        public DbSet<sessions> sessions { get; set; }
        public DbSet<settings> settings { get; set; }
        public DbSet<stamps> stamps { get; set; }
        public DbSet<subscriptions> subscriptions { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<view_preferences> view_preferences { get; set; }
        public DbSet<view_settings> view_settings { get; set; }
        public DbSet<views> views { get; set; }
        public DbSet<server> server { get; set; }
    }
}
